added config.json

diff --git a/.github/workflows/merge_and_migrate.yml b/.github/workflows/merge_and_migrate.yml
--- a/.github/workflows/merge_and_migrate.yml
+++ b/.github/workflows/merge_and_migrate.yml
@@ -1,35 +1,58 @@
 name: Migrate to Target
 
 on:
-  push:
+  pull_request:
+    types:
+      - closed
     branches:
       - main
     paths-ignore:
-      - 'README.md'
-      - 'Contributing.md'
+      - "README.md"
+      - "Contributing.md"
+      - ".github/**"
   workflow_dispatch:
     inputs:
       branch:
-        description: 'Branch to deploy'
+        description: "Branch to deploy"
         required: true
-        default: 'main'
+        default: "main"
 
 jobs:
   migrate_to_target:
     name: Migration to Target
     runs-on: ubuntu-latest
+    env:
+      SOURCE_HOST_URL: ${{ secrets.SOURCE_HOST_URL }}
+      SOURCE_TOKEN: ${{ secrets.SOURCE_TOKEN }}
+      TARGET_HOST_URL: ${{ secrets.TARGET_HOST_URL }}
+      TARGET_TOKEN: ${{ secrets.TARGET_TOKEN }}
+      
     steps:
       - name: Check out code
         uses: actions/checkout@v4
         with:
-          ref: ${{ github.event.inputs.branch || github.ref_name }}
+          ref: ${{ github.event.inputs.branch || github.event.pull_request.base.ref }}
 
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install pipx
-          LATEST_RELEASE=$(curl -s https://api.github.com/repos/StrawHatEngineer/CICD_2/releases/latest | jq -r .tag_name)
-          pipx install https://github.com/StrawHatEngineer/CICD_2/releases/download/${LATEST_RELEASE}/cicd_aihub-${LATEST_RELEASE#v}-py3-none-any.whl
+          # Attempt to install from local file first
+          VERSION=$(ls cicd_aihub-*-py3-none-any.whl | sed 's/cicd_aihub-\(.*\)-py3-none-any.whl/\1/' | head -n 1)
+
+          if [ -n "$VERSION" ]; then
+            echo "Found local .whl file: cicd_aihub-${VERSION}-py3-none-any.whl"
+            pipx install cicd_aihub-${VERSION}-py3-none-any.whl
+          else
+            echo "No local .whl file found. Attempting to install from GitHub release."
+            LATEST_RELEASE=$(curl -s https://api.github.com/repos/instabase/aihub-apps-ci-cd-workflows/releases/latest | jq -r .tag_name)
+            VERSION=$(echo $LATEST_RELEASE | sed 's/^v//')
+            
+            if ! pipx install https://github.com/instabase/aihub-apps-ci-cd-workflows/releases/download/${LATEST_RELEASE}/cicd_aihub-${VERSION}-py3-none-any.whl; then
+              echo "Failed to install from GitHub release after failing to find local .whl file. Aborting."
+              exit 1
+            fi
+          fi
 
       - name: Validate config.json
         run: |
@@ -37,13 +60,13 @@ jobs:
             echo "Error: config.json file not found"
             exit 1
           fi
-          
+
           APP_ID=$(jq -r '.source.app_id' config.json)
           if [ -z "$APP_ID" ] || [ "$APP_ID" = "null" ]; then
             echo "Error: app_id is missing or null in config.json"
             exit 1
           fi
-          
+
       - name: Migrate app to Target
         run: |
           IS_ADVANCED=$(jq -r '.source.is_advanced' config.json)
@@ -51,7 +74,8 @@ jobs:
           FLOW_PATH=$(jq -r '.source.flow_path' config.json)
           DEPLOYMENT_ID=$(jq -r '.source.deployment_id' config.json)
           DEPENDENCIES=$(jq -r '.source.dependencies' config.json)
-          
+          REBUILD=$(jq -r '.settings.rebuild' config.json)
+
           DEPLOY_FLAG=""
           if [ -n "$DEPLOYMENT_ID" ] && [ "$DEPLOYMENT_ID" != "null" ]; then
             DEPLOY_FLAG="--create_deployment"
@@ -62,10 +86,24 @@ jobs:
             DEPS_FLAG="--upload_dependencies"
           fi
 
+          REBUILD_FLAG=""
+          if [ "$REBUILD" = "true" ]; then
+            REBUILD_FLAG="--rebuild"
+          fi
+
           if [ "$IS_ADVANCED" = "true" ] && [ -n "$FLOW_PATH" ] && [ "$FLOW_PATH" != "null" ]; then
             promote-solution --promote_solution_to_target --publish_advanced_app $DEPLOY_FLAG $DEPS_FLAG
           elif [ "$IS_ADVANCED" = "true" ] && [ -n "$SB_NAME" ] && [ "$SB_NAME" != "null" ]; then
             promote-sb-solution --promote_solution_to_target --publish_advanced_app $DEPLOY_FLAG $DEPS_FLAG
           else
-            promote-build-solution --upload_binary --publish_advanced_app $DEPLOY_FLAG
+            promote-build-solution --publish_build_app $DEPLOY_FLAG $REBUILD_FLAG
           fi
+
+      - name: Create Tag for Release
+        if: success()
+        run: |
+          git config --global user.email "no-reply@github.com"
+          git config --global user.name "GitHub Actions"
+          APP_RELEASE_VERSION=$(jq -r '.version' app_details.json)
+          git tag -a "v${APP_RELEASE_VERSION}" -m "Release version ${APP_RELEASE_VERSION}"
+          git push origin "v${APP_RELEASE_VERSION}"
diff --git a/.github/workflows/regression_suite.yml b/.github/workflows/regression_suite.yml
--- a/.github/workflows/regression_suite.yml
+++ b/.github/workflows/regression_suite.yml
@@ -1,23 +1,27 @@
-name: Fetch Latest Code
+name: Regression Suite
 
 on:
-  push:
+  pull_request:
+    types:
+      - opened
     branches:
-      - feature/*
-    paths-ignore:
-      - "README.md"
-      - "Contributing.md"
+      - main
+  workflow_dispatch:
+    inputs:
+      branch:
+        description: "Branch to run regression suite"
+        required: true
+        default: "main"
 
 jobs:
-  development:
-    name: Fetch and Commit Latest Code
+  regression_suite:
+    name: Regression Suite
     runs-on: ubuntu-latest
     env:
       SOURCE_HOST_URL: ${{ secrets.SOURCE_HOST_URL }}
       SOURCE_TOKEN: ${{ secrets.SOURCE_TOKEN }}
       TARGET_HOST_URL: ${{ secrets.TARGET_HOST_URL }}
       TARGET_TOKEN: ${{ secrets.TARGET_TOKEN }}
-
     steps:
       - name: Check out code
         uses: actions/checkout@v4
@@ -26,6 +30,7 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install pipx
+          
           # Attempt to install from local file first
           VERSION=$(ls cicd_aihub-*-py3-none-any.whl | sed 's/cicd_aihub-\(.*\)-py3-none-any.whl/\1/' | head -n 1)
 
@@ -50,24 +55,33 @@ jobs:
             exit 1
           fi
 
-      - name: Fetch Latest App Data
+          APP_ID=$(jq -r '.source.app_id' config.json)
+          if [ -z "$APP_ID" ] || [ "$APP_ID" = "null" ]; then
+            echo "Error: app_id is missing or null in config.json"
+            exit 1
+          fi
+
+          REGRESSION=$(jq -r '.regression' config.json)
+          if [ -z "$REGRESSION" ] || [ "$REGRESSION" = "null" ]; then
+            echo "Error: regression is missing or null in config.json"
+            exit 1
+          fi
+
+      - name: Run regression tests
         run: |
           IS_ADVANCED=$(jq -r '.source.is_advanced' config.json)
           SB_NAME=$(jq -r '.source.sb_name' config.json)
           FLOW_PATH=$(jq -r '.source.flow_path' config.json)
-          PROJECT_ID=$(jq -r '.source.project_id' config.json)
-          if [ "$IS_ADVANCED" = "true" ] && [ -n "$FLOW_PATH" ] && [ "$FLOW_PATH" != "null" ]; then
-            promote-solution --compile_solution --download_solution
-          elif [ "$IS_ADVANCED" = "true" ] && [ -n "$SB_NAME" ] && [ "$SB_NAME" != "null" ]; then
-            promote-sb-solution --compile_solution --download_solution
-          elif [ "$IS_ADVANCED" = "false" ] && [ -n "$PROJECT_ID" ] && [ "$PROJECT_ID" != "null" ]; then
-            promote-build-solution --compile_solution --download_solution
-          else
-            echo "Error: not a valid config.json"
-            exit 1
-          fi
 
-      - name: Commit app data to feature branch
+          if [ "$IS_ADVANCED" = "true" ] && [ -n "$FLOW_PATH" ] && [ "$FLOW_PATH" != "null" ]; then
+            promote-solution --regression
+          elif [ "$IS_ADVANCED" = "true" ] && [ -n "$SB_NAME" ] && [ "$SB_NAME" != "null" ]; then
+            promote-sb-solution --regression
+          else
+            promote-build-solution --regression
+          fi
+      
+      - name: Commit regression results to feature branch
         run: |
           git config --global user.email "no-reply@github.com"
           git config --global user.name "GitHub Actions"
@@ -76,6 +90,6 @@ jobs:
           git add -f .
           git status
           git commit -m "$COMMIT_MESSAGE" --allow-empty
-          git push origin ${{ github.ref_name }}
+          git push origin HEAD:${{ github.head_ref }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
